const data = {
  products: [
    {
      name: 'fuji apples, whole',
      slug: 'apples-fuji-whole',
      image: 'fujiapples.png',
      category: 'fruit',
      storage: 'fridge',
      optimalHold: 42,
    },
    {
      name: 'oranges, whole',
      slug: 'oranges-whole',
      image: 'oranges.png',
      category: 'fruit',
      storage: 'room temperature',
      optimalHold: 10,
    },
    {
      name: 'bananas, whole',
      slug: 'bananas-whole',
      image: 'bananas.png',
      category: 'fruit',
      storage: 'room temperature',
      optimalHold: 5,
    },
    {
      name: 'grapes, green',
      slug: 'grapes-green',
      image: 'grapesgreen.png',
      category: 'fruit',
      storage: 'fridge',
      optimalHold: 7,
    },
    {
      name: 'strawberries',
      slug: 'strawberries',
      image: 'strawberries.png',
      category: 'fruit',
      storage: 'fridge',
      optimalHold: 5,
    },
    {
      name: 'peaches, whole',
      slug: 'peaches-whole',
      image: 'peacheswhole.png',
      category: 'fruit',
      storage: 'fridge',
      optimalHold: 5,
    },
    {
      name: 'cilantro, dried',
      slug: 'cilantro-dried',
      image: 'cilantrodried.png',
      category: 'veggies',
      storage: 'room temperature',
      optimalHold: 365,
    },
    {
      name: 'cilantro, fresh',
      slug: 'cilantro-fresh',
      image: 'cilantrofresh.png',
      category: 'veggies',
      storage: 'fridge',
      optimalHold: 30,
    },
    {
      name: 'cilantro, paste',
      slug: 'cilantro-paste',
      image: 'cilantropaste.png',
      category: 'veggies',
      storage: 'fridge',
      optimalHold: 100,
    },
    {
      name: 'sweet potatoes',
      slug: 'potatoes-sweet',
      image: 'sweetpotatoes.png',
      category: 'veggies',
      storage: 'countertop',
      optimalHold: 7,
    },
    {
      name: 'oat milk',
      slug: 'milk-oat',
      image: 'oatmilk.png',
      category: 'non-dairy',
      storage: 'fridge',
      optimalHold: 7,
    },
    {
      name: 'avocados',
      slug: 'avocados',
      image: 'avocados.png',
      category: 'veggies',
      storage: 'countertop',
      optimalHold: 2,
    },
    {
      name: 'whole wheat bread',
      slug: 'bread-whole-wheat',
      image: 'wholewheatbread.png',
      category: 'grains',
      storage: 'countertop',
      optimalHold: 7,
    },
    {
      name: 'spinach, fresh',
      slug: 'spinach-fresh',
      image: 'spinachfresh.png',
      category: 'veggies',
      storage: 'fridge',
      optimalHold: 10,
    },
  ],
};

export default data;
